services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./teamspend-data/db:/var/lib/postgresql/data

  api:
    build: ./
    depends_on:
      - db
    ports:
      - 3001:3000
    restart: unless-stopped
    env_file: '.env.sit'

volumes:
  teamspend-data:
