export const exceptionErrorCode = {
  GENERAL_ERROR: 'E_001',
  VALIDATION_ERROR: 'E_002',
  FORBIDDEN_RESOURCE: 'E_003',
  NOT_FOUND_RESOURCE: 'E_004',
  AUTH: {
    INCORRECT_USER_CREDENTIALS: 'EATH_001',
    EXPIRED_TOKEN: 'EATH_002',
    UNAUTHORIZED_ACCESS: 'EATH_003',
    RESTRICTECD_SELF_SESSION_REVOCATION: 'EATH_004',
  },
} as const;
