export const exceptionErrorCode = {
  GENERAL_ERROR: 'E_001',
  INCORRECT_USER_CREDENTIALS: 'E_002',
  VALIDATION_ERROR: 'E_003',
  FORBIDDEN_RESOURCE: 'E_004',
  EXPIRED_TOKEN: 'E_005',
  UNAUTHORIZED_ACCESS: 'E_006',
} as const;
