Project TeamSpend {
  database_type: 'PostgreSQL'

  Note: '''
    # TeamSpend Database
  '''
}

Table users {
  id varchar(255) [pk, note: 'uuid']
  username varchar(255) [not null, unique]
  email varchar(255) [not null, unique]
  password varchar(255) [not null]
  first_name varchar(255) [not null]
  middle_name varchar(255) 
  last_name varchar(255) [not null]
  status varchar(255) [not null, default: 'active', note: '''
    Available values: 
    - ACTIVE
    - INACTIVE
    - DELETED
    ''']
  created_at timestamp [not null, default: 'now()']
  last_modified_at timestamp

  Note: "Contains user information"
}

Table tokens {
  id varchar(255) [pk, note: 'uuid']
  subject_id varchar(255) [not null]
  type varchar(255) [not null, note: '''
    Available values: 
    - REFRESH_TOKEN
    ''']
  status varchar(255) [not null, default: 'active', note: '''
    Available values: 
    - ACTIVE
    - INACTIVE
    - DELETED
    ''']
  created_at timestamp [not null, default: 'now()']
  last_modified_at timestamp

  Note: "Contains token information"
}

Ref: users.id < sessions.user__id
Table sessions {
  id varchar(255) [pk, note: 'uuid']
  user__id varchar(255) [not null]
  type varchar(255) [not null, note: '''
    Available values: 
    - LOGIN
    - RESET_PWD
    ''']
  status varchar(255) [not null, default: 'active', note: '''
    Available values: 
    - ACTIVE
    - INACTIVE
    - DELETED
    ''']
  device_id varchar(255)
  device_name varchar(255)
  expired_at timestamp [not null]
  created_at timestamp [not null, default: 'now()']
  last_modified_at timestamp

  Note: "Contains session information"
}