Project TeamSpend {
  database_type: 'PostgreSQL'
  Note: '''
    # TeamSpend Database
  '''
}
Table User {
  id varchar(255) [pk, note: 'uuid']
  username varchar(255) [not null]
  email varchar(255) [not null]
  password varchar(255) [not null]
  first_name varchar(255) [not null]
  middle_name varchar(255) 
  last_name varchar(255) [not null]
  status varchar(255) [not null, default: 'active', note: '''
    Available values: 
    - ACTIVE
    - INACTIVE
    - DELETED
    ''']
  created_at timestamp [not null, default: 'now()']
  last_modified_at timestamp
  note: "Contains user information"

  Indexes {
    (email, status) [unique]
  }
  Indexes {
    (username, status) [unique]
  }
}